"""add resource_type and format to ride_media

Revision ID: 1014a33f0e10
Revises: ff2b1a678698
Create Date: 2026-05-11 11:58:09.284456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1014a33f0e10'
down_revision: Union[str, None] = 'ff2b1a678698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_media', sa.Column('resource_type', sa.String(length=50), nullable=True))
    op.add_column('ride_media', sa.Column('format', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride_media', 'format')
    op.drop_column('ride_media', 'resource_type')
    # ### end Alembic commands ###
