"""Add listings table

Revision ID: 280b8d389eb0
Revises: a0fa4c74bcd2
Create Date: 2026-05-11 09:45:50.015737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '280b8d389eb0'
down_revision: Union[str, None] = 'a0fa4c74bcd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('property_type', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('media_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.create_index('ix_listings_unique_property', 'listings', ['user_id', 'address', 'city', 'state', 'country'], unique=True)
    op.create_index(op.f('ix_listings_user_id'), 'listings', ['user_id'], unique=False)
    op.drop_column('users', 'address')
    op.drop_column('users', 'id_verification_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_verification_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_listings_user_id'), table_name='listings')
    op.drop_index('ix_listings_unique_property', table_name='listings')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
