"""add address and id verification fields

Revision ID: 3b7470b925d4
Revises: 4dfc639d6cf4
Create Date: 2026-05-08 05:19:06.079480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7470b925d4'
down_revision: Union[str, None] = '4dfc639d6cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('id_verification_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'id_verification_url')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
