"""sync_user_fields

Revision ID: 3f1b7d923fd8
Revises: 499376725e8e
Create Date: 2026-05-13 05:00:32.174209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f1b7d923fd8'
down_revision: Union[str, None] = '499376725e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_media_id'), table_name='ride_media')
    op.drop_index(op.f('ix_ride_media_ride_id'), table_name='ride_media')
    op.drop_table('ride_media')
    op.drop_index(op.f('ix_rides_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_unique_listing'), table_name='rides')
    op.drop_index(op.f('ix_rides_user_id'), table_name='rides')
    op.drop_table('rides')
    # Add columns if they don't exist
    conn = op.get_bind()
    columns = conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name = 'users'")).fetchall()
    existing_columns = [c[0] for c in columns]

    if 'phone_number' not in existing_columns:
        op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    if 'avatar_url' not in existing_columns:
        op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    if 'address' not in existing_columns:
        op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    if 'id_verification_url' not in existing_columns:
        op.add_column('users', sa.Column('id_verification_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'id_verification_url')
    op.drop_column('users', 'address')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone_number')
    op.create_table('ride_media',
    sa.Column('ride_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('public_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('format', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('ride_media_ride_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ride_media_pkey'))
    )
    op.create_index(op.f('ix_ride_media_ride_id'), 'ride_media', ['ride_id'], unique=False)
    op.create_index(op.f('ix_ride_media_id'), 'ride_media', ['id'], unique=False)
    op.create_table('rides',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('ride_type', postgresql.ENUM('sedan', 'suv', 'van', name='ridetype'), autoincrement=False, nullable=False),
    sa.Column('seat_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('door_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pickup_location', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('pickup_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pickup_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adult_passenger_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('children_passenger_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('infant_passenger_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'published', 'inactive', name='ridestatus'), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('rides_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rides_pkey'))
    )
    op.create_index(op.f('ix_rides_user_id'), 'rides', ['user_id'], unique=False)
    op.create_index(op.f('ix_rides_unique_listing'), 'rides', ['user_id', 'ride_type', 'seat_count', 'door_count', 'pickup_location'], unique=True)
    op.create_index(op.f('ix_rides_id'), 'rides', ['id'], unique=False)
    # ### end Alembic commands ###
