"""add_admin_rbac_columns

Revision ID: 486419238951
Revises: e45144a42028
Create Date: 2026-05-20 15:14:13.817922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486419238951'
down_revision: Union[str, None] = 'e45144a42028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # PostgreSQL enums need explicit ALTER TYPE to add new values
    op.execute("ALTER TYPE ridestatus ADD VALUE IF NOT EXISTS 'pending_approval'")
    op.execute("ALTER TYPE ridestatus ADD VALUE IF NOT EXISTS 'rejected'")
    op.execute("ALTER TYPE ridestatus ADD VALUE IF NOT EXISTS 'suspended'")

    op.add_column('properties', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('rides', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('vendor_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('vendor_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('id_verification_status', sa.String(length=50), nullable=False, server_default='none'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'id_verification_status')
    op.drop_column('users', 'vendor_verified_at')
    op.drop_column('users', 'vendor_verified')
    op.drop_column('rides', 'admin_notes')
    op.drop_column('properties', 'admin_notes')
    # ### end Alembic commands ###
