"""create_properties_table

Revision ID: 99d3d7bac4fc
Revises: b3c4d5e6f7a8
Create Date: 2026-05-13 12:01:57.416297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99d3d7bac4fc'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('type', sa.String(length=100), nullable=False),
                    sa.Column('location', sa.String(
                        length=500), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('beds', sa.Integer(), nullable=False),
                    sa.Column('baths', sa.Integer(), nullable=False),
                    sa.Column('guests', sa.JSON(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('photos', sa.JSON(), nullable=True),
                    sa.Column('video_url', sa.String(
                        length=1000), nullable=True),
                    sa.Column('amenities', sa.JSON(), nullable=True),
                    sa.Column('payout_account', sa.String(
                        length=20), nullable=True),
                    sa.Column('payout_bank', sa.String(
                        length=100), nullable=True),
                    sa.Column('payout_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'name', 'location',
                                        name='uq_property_user_name_location')
                    )
    op.create_index(op.f('ix_properties_id'),
                    'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_user_id'),
                    'properties', ['user_id'], unique=False)
    op.create_table('rides',
                    sa.Column('user_id', sa.String(length=36), nullable=False),
                    sa.Column('ride_type', sa.Enum('sedan', 'suv',
                              'van', name='ridetype'), nullable=False),
                    sa.Column('seat_count', sa.Integer(), nullable=False),
                    sa.Column('door_count', sa.Integer(), nullable=False),
                    sa.Column('pickup_location', sa.String(
                        length=255), nullable=False),
                    sa.Column('pickup_latitude', sa.Float(), nullable=True),
                    sa.Column('pickup_longitude', sa.Float(), nullable=True),
                    sa.Column('adult_passenger_count',
                              sa.Integer(), nullable=False),
                    sa.Column('children_passenger_count',
                              sa.Integer(), nullable=False),
                    sa.Column('infant_passenger_count',
                              sa.Integer(), nullable=False),
                    sa.Column('features', sa.JSON(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('currency', sa.String(
                        length=10), nullable=False),
                    sa.Column('status', sa.Enum('draft', 'published',
                                                'inactive', name='ridestatus'), nullable=True),
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_rides_id'), 'rides', ['id'], unique=False)
    op.create_index('ix_rides_unique_listing', 'rides', [
                    'user_id', 'ride_type', 'seat_count', 'door_count', 'pickup_location'], unique=True)
    op.create_index(op.f('ix_rides_user_id'), 'rides',
                    ['user_id'], unique=False)
    op.create_table('ride_media',
                    sa.Column('ride_id', sa.String(length=36), nullable=False),
                    sa.Column('media_type', sa.String(
                        length=50), nullable=False),
                    sa.Column('url', sa.String(length=255), nullable=False),
                    sa.Column('public_id', sa.String(
                        length=255), nullable=False),
                    sa.Column('resource_type', sa.String(
                        length=50), nullable=True),
                    sa.Column('format', sa.String(length=50), nullable=True),
                    sa.Column('position', sa.Integer(), nullable=True),
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['ride_id'], ['rides.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_ride_media_id'),
                    'ride_media', ['id'], unique=False)
    op.create_index(op.f('ix_ride_media_ride_id'),
                    'ride_media', ['ride_id'], unique=False)
    op.alter_column('support_tickets', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('support_tickets', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_support_tickets_id'),
                    'support_tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.alter_column('support_tickets', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('support_tickets', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ride_media_ride_id'), table_name='ride_media')
    op.drop_index(op.f('ix_ride_media_id'), table_name='ride_media')
    op.drop_table('ride_media')
    op.drop_index(op.f('ix_rides_user_id'), table_name='rides')
    op.drop_index('ix_rides_unique_listing', table_name='rides')
    op.drop_index(op.f('ix_rides_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_index(op.f('ix_properties_user_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
