"""Add rides and remove listings

Revision ID: ff2b1a678698
Revises: 280b8d389eb0
Create Date: 2026-05-11 10:25:40.527237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff2b1a678698'
down_revision: Union[str, None] = '280b8d389eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rides',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ride_type', sa.Enum('sedan', 'suv', 'van', name='ridetype'), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('door_count', sa.Integer(), nullable=False),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('pickup_latitude', sa.Float(), nullable=True),
    sa.Column('pickup_longitude', sa.Float(), nullable=True),
    sa.Column('adult_passenger_count', sa.Integer(), nullable=False),
    sa.Column('children_passenger_count', sa.Integer(), nullable=False),
    sa.Column('infant_passenger_count', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'inactive', name='ridestatus'), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rides_id'), 'rides', ['id'], unique=False)
    op.create_index('ix_rides_unique_listing', 'rides', ['user_id', 'ride_type', 'seat_count', 'door_count', 'pickup_location'], unique=True)
    op.create_index(op.f('ix_rides_user_id'), 'rides', ['user_id'], unique=False)
    op.create_table('ride_media',
    sa.Column('ride_id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_media_id'), 'ride_media', ['id'], unique=False)
    op.create_index(op.f('ix_ride_media_ride_id'), 'ride_media', ['ride_id'], unique=False)
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_unique_property'), table_name='listings')
    op.drop_index(op.f('ix_listings_user_id'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('property_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('bedrooms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bathrooms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_urls', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('listings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('listings_pkey'))
    )
    op.create_index(op.f('ix_listings_user_id'), 'listings', ['user_id'], unique=False)
    op.create_index(op.f('ix_listings_unique_property'), 'listings', ['user_id', 'address', 'city', 'state', 'country'], unique=True)
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.drop_index(op.f('ix_ride_media_ride_id'), table_name='ride_media')
    op.drop_index(op.f('ix_ride_media_id'), table_name='ride_media')
    op.drop_table('ride_media')
    op.drop_index(op.f('ix_rides_user_id'), table_name='rides')
    op.drop_index('ix_rides_unique_listing', table_name='rides')
    op.drop_index(op.f('ix_rides_id'), table_name='rides')
    op.drop_table('rides')
    # ### end Alembic commands ###
